jobs:
- name: (( grab meta.unit_test.name || "not-defined" ))
  plan:
  - get: (( grab meta.git.app-name ))
    trigger: (( grab meta.git.trigger ))
  - task: unit_test
    config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: (( grab meta.unit_test.docker-image || nil ))
        inputs:
        - name: (( grab meta.git.app-name ))
        run:
          path: sh
          args:
          - (( concat meta.git.app-name "/" meta.unit_test.script || nil ))

- name: (( concat "cf-push-" meta.git.app-name ))
  plan:
  - get: (( grab meta.git.app-name ))
    trigger: (( grab meta.git.trigger ))
    passed:
    - (( grab meta.unit_test.name || "(( prune ))" ))
  - put: (( concat "cf-push-" meta.git.app-name ))
    params:
      manifest: (( concat meta.git.app-name "/manifest.yml" ))

resources:
- name: (( grab meta.git.app-name ))
  type: git
  source:
    uri: (( grab meta.git.ssh ))
    private_key: (( grab meta.git.private-key || "(( prune ))" ))
    branch: (( grab meta.git.branch ))

- name: (( concat "cf-push-" meta.git.app-name ))
  type: cf
  source:
    api: (( grab meta.cf.api ))
    username: (( grab meta.cf.username ))
    password: (( grab meta.cf.password ))
    organization: (( grab meta.cf.org ))
    space: (( grab meta.cf.space ))
    skip_cert_check: (( grab meta.cf.skip_cert_check ))
    docker_username: (( grab meta.cf.docker_username || "(( prune ))" ))
    docker_password: (( grab meta.cf.docker_password || "(( prune ))" ))
